/*
 * Copyright (C) Evan Stoddard
 */

/**
 * @file device.h
 * @author Evan Stoddard
 * @brief
 */

#ifndef LIBDEV_DEVICE_H
#define LIBDEV_DEVICE_H

#include "device_priv.h"

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * Structs, Unions, Enums, & Typedefs
 *****************************************************************************/

/**
 * @typedef device
 * @brief Device instance
 *
 */
struct device {
  void *config;
  void *data;
  void *api;
};

/*****************************************************************************
 * Declaration Macros
 *****************************************************************************/

/**
 * @brief Used to declare an attribute for a device instance
 * @param name Instance name
 * @param key Key of attribute
 * @param val Value of attribute
 */
#define LIBDEV_DEVICE_ATTR(inst_name, key, val)

/* Expand the project's device.def once, emitting an extern for every
 * instance. LIBDEV_DEVICE is redefined to nothing afterward so any later
 * expansion of a def entry in this translation unit is a no-op. */

/**
 * @brief Used to declare a device instance in the def file.  Emits an extern
 * for for every device instance that gets defined in the instance's appropriate
 * driver implementation.  Gets resolved to a pointer with the LIBDEV_DEVICE_GET
 * macro.
 *
 * @param inst_name Instance name
 * @param compat Compatiblity token used to resolve the instances device driver
 * implementation
 * @param base_addr Multi-use, either memory mapped address for things like
 * flash, or i2c address, etc
 * @param parent_dev Parent device instance, for instance the i2c bus an i2c
 * sensor is a child of.
 */
#define LIBDEV_DEVICE(name, compat, base_addr, parent_dev)                     \
  extern const struct device LIBDEV_DEV_INST_NAME(name);

/*
 * Include definition file
 */
#include LIBDEV_DEFINITION_INCLUDE
#undef LIBDEV_DEVICE

/* Generated expanded macros and definitions based on definition file.  Safe to
 * unconditionally include.  This gets generated by the build system to provide
 * additional context for each device instance that is resolved by macros below,
 * as well as driver implementations. */
#include "device_instances.inc"

/**
 * @def LIBDEV_INST_FOREACH
 * @brief Invokes fn(name) for every device.def instance of the driver's
 *        compat
 *
 * The driver must define LIBDEV_DRV_COMPAT (its compat token) before
 * invoking this, analogous to Zephyr's DT_DRV_COMPAT +
 * DT_INST_FOREACH_STATUS_OKAY(fn).
 *
 * @param fn Macro defined by specific driver implementation for devicing a
 * driver instance.  Will ultimately call LIBDEV_DEVICE_DEFINE
 */
#define LIBDEV_INST_FOREACH(fn)                                                \
  LIBDEV_CONCAT(LIBDEV_FOREACH_, LIBDEV_DRV_COMPAT)(fn)

/**
 * @def LIBDEV_DEVICE_DEFINE
 * @brief Defines the struct device instance for a device.def entry
 *
 * Invoked from a driver's per-instance init macro (via
 * LIBDEV_INST_FOREACH), analogous to Zephyr's DEVICE_DT_INST_DEFINE.
 *
 * @param _inst_name Device instance name
 * @param _api Pointer to driver implementation's API struct
 * @param _config Pointer to device instance's config pointer
 * @param _data Pointer to device instance's data pointer
 */
#define LIBDEV_DEVICE_DEFINE(_inst_name, _api, _config, _data)                 \
  const struct device LIBDEV_DEV_INST_NAME(_inst_name) = {                     \
      .config = (_config), .data = (_data), .api = (_api)};

/**
 * @def LIBDEV_DEVICE_GET
 * @brief Retrieves the struct device pointer for a device instance by name
 *
 * @param inst_name Instance name
 */
#define LIBDEV_DEVICE_GET(inst_name) (&LIBDEV_DEV_INST_NAME(inst_name))

/**
 * @brief Returns value of base_addr declared for device in def file.
 *
 * @param Instance name
 */
#define LIBDEV_DEVICE_GET_BASE_ADDR(inst_name)                                 \
  LIBDEV_DEVICE_##inst_name##_BASE_ADDR

/**
 * @brief Gets pointer to a parent device's device instance struct
 *
 * @param Instance name
 */
#define LIBDEV_DEVICE_GET_PARENT_DEV_INST(inst_name)                           \
  LIBDEV_DEVICE_GET(LIBDEV_DEVICE_##inst_name##_PARENT_DEV)

/**
 * @brief Gets value of a device instances attribute as declared in the def
 * file.
 *
 * @param inst_name Instance name
 * @param key Key to fetch value for.
 */
#define LIBDEV_DEVICE_GET_ATTR(inst_name, key)                                 \
  (LIBDEV_DEVICE_INST_##inst_name##_ATTR_##key)

#ifdef __cplusplus
}
#endif
#endif /* LIBDEV_DEVICE_H */
