#!/usr/bin/env python3
"""Generate device_instances.inc from a device.def file.

Groups LIBDEV_DEVICE(name, compat) entries by compat and emits one
LIBDEV_FOREACH_<COMPAT>(fn) macro per compat, expanding to fn(name) for
every instance of that compat. A driver invokes its own foreach macro
with its own per-instance definition macro as the argument, e.g.
LIBDEV_FOREACH_STM32_INTERNAL_FLASH(STM32_INTERNAL_FLASH_DEFINE).
"""
import re
import sys
from collections import OrderedDict

ENTRY_RE = re.compile(r"LIBDEV_DEVICE\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)")


def parse(def_path):
    groups = OrderedDict()
    with open(def_path) as f:
        for line in f:
            match = ENTRY_RE.search(line)
            if match:
                name, compat = match.groups()
                groups.setdefault(compat, []).append(name)
    return groups


def render(groups):
    lines = ["/* AUTO-GENERATED by gen_device_instances.py. Do not edit. */", ""]
    for compat, names in groups.items():
        args = " ".join(f"fn({name})" for name in names)
        lines.append(f"#define LIBDEV_FOREACH_{compat}(fn) {args}")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <device.def> <output.inc>")

    def_path, out_path = sys.argv[1], sys.argv[2]
    groups = parse(def_path)
    with open(out_path, "w") as f:
        f.write(render(groups))


if __name__ == "__main__":
    main()
