#!/usr/bin/env python3
"""Generate device_instances.inc from a device.def file.

Groups LIBDEV_DEVICE(name, compat) entries by compat and emits one
LIBDEV_FOREACH_<COMPAT>(fn) macro per compat, expanding to fn(name) for
every instance of that compat. A driver invokes its own foreach macro
with its own per-instance definition macro as the argument, e.g.
LIBDEV_FOREACH_STM32_INTERNAL_FLASH(STM32_INTERNAL_FLASH_DEFINE).
"""
import re
import sys
from collections import OrderedDict

# Matches the following LIBDEV_DEVICE(device_name, device_compat, device_addr)
DEVICE_INST_RE = re.compile(r"LIBDEV_DEVICE\s*\(\s*(\w+)\s*,\s*(\w+)\s*\,\s*(\w+)\s*\,\s*(\w+)\s*\)")

# Matches the following LIBDEV_DEVICE_ATTR(device_name, attr_key, attr_val)
DEVICE_ATTR_INST_RE = re.compile(r"LIBDEV_DEVICE_ATTR\s*\(\s*(\w+)\s*,\s*(\w+)\s*\,\s*(\w+)\s*\)")

def parse_devices(def_path):
    devices = []

    with open(def_path) as f:
        for line in f:
            match = DEVICE_INST_RE.search(line)
            if match:
                name, compat, base_addr, parent_dev = match.groups()
                devices.append((name, compat, base_addr, parent_dev))
        
        return devices 

def parse_device_attributes(def_path):
    attr_tuples = []

    with open(def_path) as f:
        for line in f:
            match = DEVICE_ATTR_INST_RE.search(line)
            if match:
                attr_tuples.append(match.groups())

    return attr_tuples


def render_devices(devices):
    lines = ["/* Root Devices */"]
    
    compat_map = {} 

    for name, compat, base_addr, parent_dev in devices:
        compat_str = f"{compat}"
        compat_map.setdefault(compat_str, []).append(f"fn({name})")
        lines.append(f"#define LIBDEV_DEVICE_{name}_BASE_ADDR {base_addr}")
        lines.append(f"#define LIBDEV_DEVICE_{name}_PARENT_DEV {parent_dev}")
        lines.append("")

    for key, invocations in compat_map.items():
        lines.append(f"#define LIBDEV_FOREACH_{key}(fn) {' '.join(invocations)}")

    return "\n".join(lines) + "\n" 

def render_attributes(attributes):
    lines = ["/* Device Attributes */"]

    for device_name, attr_key, attr_val in attributes:
        lines.append(f"#define LIBDEV_DEVICE_INST_{device_name}_ATTR_{attr_key} {attr_val}")
    return "\n".join(lines) + "\n\n"

def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <device.def> <output.inc>")

    def_path, out_path = sys.argv[1], sys.argv[2]
    
    # Parse input file
    root_devices = parse_devices(def_path)
    device_attributes = parse_device_attributes(def_path)


    with open(out_path, "w") as f:
        header = ["/* AUTO-GENERATED by gen_device_instances.py. Do not edit. */", ""]
        f.write("\n".join(header) + "\n")
        f.write(render_devices(root_devices))
        f.write(render_attributes(device_attributes))

if __name__ == "__main__":
    main()
